// <auto-generated />
using System;
using LiveMetal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiveMetal.Infrastructure.Migrations
{
    [DbContext(typeof(LiveMetalDbContext))]
    [Migration("20240416181023_AddImageUrlToNewsAndDbSeed")]
    partial class AddImageUrlToNewsAndDbSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dea12856-c198-4129-b3f3-b893d8395082",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31b6f055-cbb3-4da1-883d-7e462e4617b0",
                            Email = "guest@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Guest",
                            LastName = "Guestov",
                            LockoutEnabled = false,
                            NormalizedEmail = "guest@mail.com",
                            NormalizedUserName = "guest@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEChGaYYEbO5BvEb1ymeNSfPw2WMX02QtPjJOeJ0t+67lVECpz05AIIoGBX9gIzPxVw==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://ohsobserver.com/wp-content/uploads/2022/12/Guest-user.png",
                            SecurityStamp = "f10f67b2-3371-44ed-b098-b3f0c6e5fedd",
                            TwoFactorEnabled = false,
                            UserName = "guest@mail.com"
                        },
                        new
                        {
                            Id = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1adec321-0e0c-4166-8088-6bbc2cafa560",
                            Email = "registered@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Registered",
                            LastName = "Registeredov",
                            LockoutEnabled = false,
                            NormalizedEmail = "registered@mail.com",
                            NormalizedUserName = "registered@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEN9Mmv5yEp7sF0Fo63eIE5fC+Bh5vnH70KbFujMhozh2PQTPf2WunkfRcY0KaiDupw==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://www.pngkey.com/png/detail/73-730394_admin-approved-user-registration-user-registration-icon-png.png",
                            SecurityStamp = "9133152c-5caf-4dda-9a04-d75f4e78fa5b",
                            TwoFactorEnabled = false,
                            UserName = "registered@mail.com"
                        },
                        new
                        {
                            Id = "f3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11585dc2-f99b-4c1f-928b-3b256dc4d0a1",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Adminov",
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@mail.com",
                            NormalizedUserName = "admin@mail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEAsr8X/QTwonesTFXF/pcESpfijnCJ62Q2dYceiAalQXqYP3avEPGDvnErP9/yypgw==",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "https://www.wpeka.com/rgh/wp-content/uploads/2014/03/Changing-the-default-admin-user-in-WordPress1-e1462965535256.jpg",
                            SecurityStamp = "64069e82-fae8-4bf9-857a-8654b01d4692",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        });
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Band", b =>
                {
                    b.Property<int>("BandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Band unique identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BandId"), 1L, 1);

                    b.Property<string>("BandImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Band image URL");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Band biography");

                    b.Property<DateTime>("FormationYear")
                        .HasColumnType("datetime2")
                        .HasComment("Band formation year");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Band genre");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Band name");

                    b.HasKey("BandId");

                    b.ToTable("Bands");

                    b.HasComment("Band Information");

                    b.HasData(
                        new
                        {
                            BandId = 1,
                            BandImageUrl = "https://w0.peakpx.com/wallpaper/812/225/HD-wallpaper-iron-maiden-the-trooper-music-band-trooper-flag-metal-iron-maiden-logo-heavy-iron-eddie-sword-maiden.jpg",
                            Biography = "Iron Maiden are an English heavy metal band formed in Leyton, East London, in 1975 by bassist and primary songwriter Steve Harris. The band's discography has grown to 40 albums, including 16 studio albums, 13 live albums, four EPs, and seven compilations.",
                            FormationYear = new DateTime(1975, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Heavy Metal",
                            Name = "Iron Maiden"
                        },
                        new
                        {
                            BandId = 2,
                            BandImageUrl = "https://i.pinimg.com/originals/04/8a/f7/048af73296084481c48c99c5f70ab378.jpg",
                            Biography = "Metallica is an American heavy metal band. The band was formed in 1981 in Los Angeles by vocalist/guitarist James Hetfield and drummer Lars Ulrich, and has been based in San Francisco for most of its career.",
                            FormationYear = new DateTime(1981, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Thrash Metal",
                            Name = "Metallica"
                        },
                        new
                        {
                            BandId = 3,
                            BandImageUrl = "https://static.wikia.nocookie.net/logopedia/images/6/6f/Nileband_logo.jpg/revision/latest?cb=20160624042213",
                            Biography = "Nile is an American death metal band from Greenville, South Carolina, formed in 1993. The band is known for its technical and complex style of death metal.",
                            FormationYear = new DateTime(1993, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Death Metal",
                            Name = "Nile"
                        },
                        new
                        {
                            BandId = 4,
                            BandImageUrl = "https://i.pinimg.com/originals/b6/30/32/b630323cff6fdfe395e5127fb73a45e3.jpg",
                            Biography = "Darkthrone is a Norwegian black metal band. It formed in 1986 as a death metal band under the name Black Death. In 1991, the band embraced a black metal style influenced by Bathory and Celtic Frost and became one of the leading bands in the Norwegian black metal scene.",
                            FormationYear = new DateTime(1986, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Black Metal",
                            Name = "Darkthrone"
                        });
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Concert unique identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConcertId"), 1L, 1);

                    b.Property<int>("BandId")
                        .HasColumnType("int")
                        .HasComment("Band unique identifier - foreign key");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Concert date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Concert description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Concert name");

                    b.Property<decimal>("TicketPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Concert ticket price");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2")
                        .HasComment("Concert time");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasComment("Venue unique identifier - foreign key");

                    b.HasKey("ConcertId");

                    b.HasIndex("BandId");

                    b.HasIndex("VenueId");

                    b.ToTable("Concerts");

                    b.HasComment("Concert Information");

                    b.HasData(
                        new
                        {
                            ConcertId = 1,
                            BandId = 1,
                            Date = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Iron Maiden are coming to London as part of their Legacy of the Beast Tour. Don't miss this unique opportunity to see one of the greatest heavy metal bands of all time!",
                            Name = "Iron Maiden - Legacy of the Beast Tour",
                            TicketPrice = 50m,
                            Time = new DateTime(2024, 6, 1, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            VenueId = 1
                        },
                        new
                        {
                            ConcertId = 2,
                            BandId = 2,
                            Date = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Metallica are coming to London as part of their WorldWired Tour. Don't miss this unique opportunity to see one of the greatest thrash metal bands of all time!",
                            Name = "Metallica - WorldWired Tour",
                            TicketPrice = 60m,
                            Time = new DateTime(2024, 7, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            VenueId = 2
                        },
                        new
                        {
                            ConcertId = 3,
                            BandId = 3,
                            Date = new DateTime(2024, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nile are coming to London as part of their Vile Nilotic Rites Tour. Don't miss this unique opportunity to see one of the greatest death metal bands of all time!",
                            Name = "Nile - Vile Nilotic Rites Tour",
                            TicketPrice = 40m,
                            Time = new DateTime(2024, 8, 30, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            VenueId = 3
                        });
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Member unique identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"), 1L, 1);

                    b.Property<int>("BandId")
                        .HasColumnType("int")
                        .HasComment("Band unique identifier - foreign key");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasComment("Member biography");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasComment("Member date of birth");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2")
                        .HasComment("Member date of joining");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Member full name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Member role");

                    b.HasKey("MemberId");

                    b.HasIndex("BandId");

                    b.ToTable("Members");

                    b.HasComment("Member Information");

                    b.HasData(
                        new
                        {
                            MemberId = 1,
                            BandId = 1,
                            Biography = "Stephen Percy Harris (born 12 March 1956) is an English musician who is the bassist, keyboardist, backing vocalist, primary songwriter and founder of heavy metal band Iron Maiden.",
                            DateOfBirth = new DateTime(1956, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(1975, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Steve Harris",
                            Role = "Bass Guitar"
                        },
                        new
                        {
                            MemberId = 2,
                            BandId = 1,
                            Biography = "David Michael Murray (born 23 December 1956) is an English guitarist and songwriter best known as one of the earliest members of the British heavy metal band Iron Maiden.",
                            DateOfBirth = new DateTime(1956, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(1976, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Dave Murray",
                            Role = "Lead Guitar"
                        },
                        new
                        {
                            MemberId = 3,
                            BandId = 2,
                            Biography = "Lars Ulrich (born 26 December 1963) is a Danish musician best known as the drummer and co-founder of American heavy metal band Metallica.",
                            DateOfBirth = new DateTime(1963, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(1981, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lars Ulrich",
                            Role = "Drums"
                        },
                        new
                        {
                            MemberId = 4,
                            BandId = 3,
                            Biography = "Karl Sanders (born 5 June 1964) is an American musician, most widely known as the founding member of the American death metal band Nile.",
                            DateOfBirth = new DateTime(1964, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(1993, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Karl Sanders",
                            Role = "Guitar"
                        },
                        new
                        {
                            MemberId = 5,
                            BandId = 4,
                            Biography = "Gylve Fenris Nagell (born 28 November 1971), better known as Fenriz, is a Norwegian musician and politician who is best known as being one half of the metal duo Darkthrone.",
                            DateOfBirth = new DateTime(1971, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(1986, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Fenriz",
                            Role = "Drums"
                        });
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("News unique identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("News content");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("News image URL");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2")
                        .HasComment("News publication date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("News title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User unique identifier - foreign key");

                    b.HasKey("NewsId");

                    b.HasIndex("UserId");

                    b.ToTable("News");

                    b.HasComment("News Information");

                    b.HasData(
                        new
                        {
                            NewsId = 1,
                            Content = "Iron Maiden have announced that they are working on a new album. The band's bassist and primary songwriter Steve Harris has revealed that the new album will be released in 2023.",
                            ImageUrl = "https://pbs.twimg.com/media/FwBzG3UXgAARJAW.jpg:large",
                            PublishedOn = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Maiden announce new album!",
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1"
                        },
                        new
                        {
                            NewsId = 2,
                            Content = "Metallica have announced that they are releasing a new single. The band's drummer Lars Ulrich has revealed that the new single will be released in 2023.",
                            ImageUrl = "https://www.rollingstone.com/wp-content/uploads/2023/07/new-Metallica-theatrical-trailer.jpg",
                            PublishedOn = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Metallica to release new single!",
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1"
                        },
                        new
                        {
                            NewsId = 3,
                            Content = "Nile have announced that they are embarking on a European tour. The band's guitarist Karl Sanders has revealed that the tour will start in 2023.",
                            ImageUrl = "https://label.napalmrecords.com/images/bands/nile/2021-nile-band-picture-press.jpg",
                            PublishedOn = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nile to embark on European tour!",
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1"
                        });
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Review unique identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"), 1L, 1);

                    b.Property<int?>("BandId")
                        .HasColumnType("int")
                        .HasComment("Band unique identifier - foreign key");

                    b.Property<int?>("ConcertId")
                        .HasColumnType("int")
                        .HasComment("Concert unique identifier - foreign key");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Review content");

                    b.Property<DateTime>("IssuedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Review publication date");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasComment("Review rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Review title");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User unique identifier - foreign key");

                    b.HasKey("ReviewId");

                    b.HasIndex("BandId");

                    b.HasIndex("ConcertId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasComment("Review Information");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            BandId = 1,
                            ConcertId = 1,
                            Content = "This was the best concert I've ever been to! Iron Maiden were amazing!",
                            IssuedOn = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            Title = "Amazing concert!",
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1"
                        },
                        new
                        {
                            ReviewId = 2,
                            BandId = 2,
                            ConcertId = 2,
                            Content = "Metallica were awesome! I had a great time at the concert!",
                            IssuedOn = new DateTime(2024, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 4,
                            Title = "Great show!",
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1"
                        },
                        new
                        {
                            ReviewId = 3,
                            BandId = 3,
                            ConcertId = 3,
                            Content = "Nile were brutal! I loved every second of the concert!",
                            IssuedOn = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5,
                            Title = "Brutal performance!",
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1"
                        });
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.UserFavourite", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User unique identifier");

                    b.Property<int>("BandId")
                        .HasColumnType("int")
                        .HasComment("Band unique identifier");

                    b.HasKey("UserId", "BandId");

                    b.HasIndex("BandId");

                    b.ToTable("UsersFavourites");

                    b.HasComment("User Favourite Bands");

                    b.HasData(
                        new
                        {
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1",
                            BandId = 1
                        },
                        new
                        {
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1",
                            BandId = 2
                        },
                        new
                        {
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1",
                            BandId = 3
                        });
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Venue unique identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasComment("Venue capacity");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Venue contact information");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasComment("Venue latitude");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Venue location");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasComment("Venue longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Venue name");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");

                    b.HasComment("Venue Information");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Capacity = 20000,
                            ContactInfo = "+44 20 8463 2000",
                            Latitude = 0.0,
                            Location = "Peninsula Square, London SE10 0DX, United Kingdom",
                            Longitude = 0.0,
                            Name = "O2 Arena"
                        },
                        new
                        {
                            VenueId = 2,
                            Capacity = 90000,
                            ContactInfo = "+44 20 8795 9000",
                            Latitude = 0.0,
                            Location = "Wembley, London HA9 0WS, United Kingdom",
                            Longitude = 0.0,
                            Name = "Wembley Stadium"
                        },
                        new
                        {
                            VenueId = 3,
                            Capacity = 5200,
                            ContactInfo = "+44 20 7589 8212",
                            Latitude = 0.0,
                            Location = "Kensington Gore, London SW7 2AP, United Kingdom",
                            Longitude = 0.0,
                            Name = "Royal Albert Hall"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "user:fullname",
                            ClaimValue = "Guest Guestov",
                            UserId = "dea12856-c198-4129-b3f3-b893d8395082"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "user:fullname",
                            ClaimValue = "Registered Registeredov",
                            UserId = "a1b1c1d1-e1f1-1g1h-1i1j-1k1l1m1n1o1"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "user:fullname",
                            ClaimValue = "Admin Adminov",
                            UserId = "f3b3b3b3-3b3b-3b3b-3b3b-3b3b3b3b3b3b"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Concert", b =>
                {
                    b.HasOne("LiveMetal.Infrastructure.Data.Models.Band", "Band")
                        .WithMany("Concerts")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiveMetal.Infrastructure.Data.Models.Venue", "Venue")
                        .WithMany("Concerts")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Member", b =>
                {
                    b.HasOne("LiveMetal.Infrastructure.Data.Models.Band", "Band")
                        .WithMany("BandMembers")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.News", b =>
                {
                    b.HasOne("LiveMetal.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany("NewsByUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Review", b =>
                {
                    b.HasOne("LiveMetal.Infrastructure.Data.Models.Band", "Band")
                        .WithMany("Reviews")
                        .HasForeignKey("BandId");

                    b.HasOne("LiveMetal.Infrastructure.Data.Models.Concert", "Concert")
                        .WithMany("Reviews")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LiveMetal.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Concert");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.UserFavourite", b =>
                {
                    b.HasOne("LiveMetal.Infrastructure.Data.Models.Band", "Band")
                        .WithMany("UserFavourites")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiveMetal.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany("UserFavourites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LiveMetal.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LiveMetal.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiveMetal.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LiveMetal.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("NewsByUser");

                    b.Navigation("Reviews");

                    b.Navigation("UserFavourites");
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Band", b =>
                {
                    b.Navigation("BandMembers");

                    b.Navigation("Concerts");

                    b.Navigation("Reviews");

                    b.Navigation("UserFavourites");
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Concert", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LiveMetal.Infrastructure.Data.Models.Venue", b =>
                {
                    b.Navigation("Concerts");
                });
#pragma warning restore 612, 618
        }
    }
}
